# Generated by Django 4.0.1 on 2022-01-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('word_level', models.CharField(choices=[('PK', 'Pre-Kindergarten'), ('KG', 'Kindergarten'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3')], max_length=2)),
            ],
        ),
    ]
