# Generated by Django 4.0.1 on 2022-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_rename_words_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='word_length',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
