# Generated by Django 4.0.1 on 2022-02-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_word_source_word_word_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_level',
            field=models.CharField(choices=[('', ''), ('PK', 'Pre-Kindergarten'), ('KG', 'Kindergarten'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3')], max_length=2, null=True),
        ),
    ]
